package pe.egcc.mifinal.view;

import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import pe.egcc.mifinal.controller.FinalController;
import pe.egcc.mifinal.model.Combo;

public class ConsultaView extends javax.swing.JInternalFrame {

  private FinalController finalController;
  
  public ConsultaView() {
    initComponents();
    finalController = new FinalController();
    llenarComboTipo();
  }
  
  private void llenarComboTipo(){
    List<Combo> lista = finalController.leerTipos();
    fillCombo(cboTipo, lista);
  }
  
  private void fillCombo(JComboBox<Combo> control, 
          List<Combo> lista) {
    
    control.removeAllItems();
    for (Combo combo : lista) {
      control.addItem(combo);
    }
    
    control.setSelectedIndex(-1);
    
  }  
  

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    cboTipo = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    cboPublica = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblRepo = new javax.swing.JTable();

    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("CONSULTAS VENTAS");

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Tipo");

    cboTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    cboTipo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboTipoActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText("Publicación");

    cboPublica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    cboPublica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboPublicaActionPerformed(evt);
      }
    });

    tblRepo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    tblRepo.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tblRepo.setRowHeight(25);
    jScrollPane1.setViewportView(tblRepo);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(28, Short.MAX_VALUE))
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cboPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
    cboPublica.removeAllItems();
    Integer index = cboTipo.getSelectedIndex();
    if( index == -1 ){
      return;
    }
    Combo tipo = (Combo) cboTipo.getSelectedItem();
    List<Combo> lista;
    lista = finalController.leerPublicaciones(tipo.getCode());
    fillCombo(cboPublica, lista);
  }//GEN-LAST:event_cboTipoActionPerformed

  private void cboPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPublicaActionPerformed
    DefaultTableModel tabla;
    tabla = (DefaultTableModel) tblRepo.getModel();
    tabla.setRowCount(0);
    
    Integer index = cboPublica.getSelectedIndex();
    if( index == -1){
      return;
    }
    
    Combo combo = (Combo) cboPublica.getSelectedItem();
    List<Map<String,Object>> ventas;
    ventas = finalController.leerVentas(combo.getCode());
    
    for (Map<String, Object> venta : ventas) {
      Object[] rowData = {
        venta.get("idventa"),
        venta.get("cliente"),
        venta.get("total")
      };
      tabla.addRow(rowData);
    }
    
  }//GEN-LAST:event_cboPublicaActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<Combo> cboPublica;
  private javax.swing.JComboBox<Combo> cboTipo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblRepo;
  // End of variables declaration//GEN-END:variables

  
}
