/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.uch.simplefactory.view;

import pe.uch.simplefactory.model.cambioModel;
import pe.uch.simplefactory.service.cambioFactory;

/**
 *
 * @author FULL
 */
public class cambioView extends javax.swing.JFrame {

    /**
     * Creates new form cambioView
     */
    public cambioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcesar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        cboTipo = new javax.swing.JComboBox<>();
        txtcantidad = new javax.swing.JTextField();
        lblCA = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 150, 60));

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipo.setText("Tipo de cambio :");
        lblTipo.setToolTipText("");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 40));

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 740, 240));

        cboTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dolar", "Euro", "Peso" }));
        getContentPane().add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 40));
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 140, 40));

        lblCA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCA.setText("Cantidad de Soles:");
        lblCA.setToolTipText("");
        getContentPane().add(lblCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 40));

        txtF.setEditable(false);
        txtF.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        procesar();
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambioView().setVisible(true);
            }
        });
    }
private void procesar (){
    double soles= Double.parseDouble(txtcantidad.getText());
     String Cambio = cboTipo.getSelectedItem().toString();
    cambioModel cm = cambioFactory.getCambio(soles, tipoCambio(Cambio));
    
    txtSalida.setText(null);
    txtSalida.append("Cambio de soles a: \t"+ cm.getTipoCambio()+"\n");
    txtSalida.append("Valor en soles   : \t"+ cm.getSoles()+"\n");
    txtSalida.append("Usted tiene      : \t"+ cm.getCambio()+" "+ cm.getTipoCambio());
    
    txtcantidad.setText(null);
    cboTipo.setSelectedIndex(0);
    cboTipo.requestFocus();
    
}
private String tipoCambio(String cambio){
    cambioModel cm=new cambioModel();
   
switch(cambio){
    case "Dolar" : cm.setTipoCambio("dolar"); break;
    case "Euro" : cm.setTipoCambio("euro"); break;
    case "Peso" : cm.setTipoCambio("peso"); break;    
}
        return cambio;

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCA;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
