package pe.egcc.colegioapp.view;

import pe.egcc.colegioapp.util.UtilView;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pe.egcc.colegioapp.controller.SeccionesController;
import pe.egcc.colegioapp.model.Combo;
import pe.egcc.colegioapp.model.Seccion;
import pe.egcc.colegioapp.util.Memoria;

public class ProgramarSeccionView extends javax.swing.JInternalFrame {

  private SeccionesController seccionesController;
  private List<Seccion> secciones = null;

  /**
   * Creates new form ProgramarSeccionView
   */
  public ProgramarSeccionView() {
    initComponents();
    seccionesController = new SeccionesController();
    llenarPeriodos();
    llenarNiveles();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    cboPeriodo = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    cboNivel = new javax.swing.JComboBox<>();
    btnNuevo = new javax.swing.JButton();
    btnEditar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    btnCerrar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblData = new javax.swing.JTable();

    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("PROGRAMAR SECCION");

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Periodo");

    cboPeriodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    cboPeriodo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboPeriodoActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText("Nivel");

    cboNivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    cboNivel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboNivelActionPerformed(evt);
      }
    });

    btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnNuevo.setText("Nuevo");
    btnNuevo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNuevoActionPerformed(evt);
      }
    });

    btnEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnEditar.setText("Editar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnCerrar.setText("Cerrar");
    btnCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCerrarActionPerformed(evt);
      }
    });

    tblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    tblData.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String [] {
        "SECCION", "NOMBRE", "PERIODO", "GRADO", "VACANTES", "MATRICULADOS"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblData.setRowHeight(30);
    jScrollPane1.setViewportView(tblData);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
              .addComponent(cboPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 10, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(cboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivelActionPerformed
      cargarSecciones();
    }//GEN-LAST:event_cboNivelActionPerformed

    private void cboPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPeriodoActionPerformed
      cargarSecciones();
    }//GEN-LAST:event_cboPeriodoActionPerformed

  private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

    if (!hayCriterio()) {
      return;
    }

    Combo periodo = (Combo) cboPeriodo.getSelectedItem();
    Combo nivel = (Combo) cboNivel.getSelectedItem();

    Seccion seccion = new Seccion();
    seccion.setPeriodo(periodo.getCode());
    seccion.setNivel(nivel.getCode());
    seccion.setNomnivel(nivel.getLabel());

    Memoria.put("accion", UtilView.CRUD_NUEVO);
    Memoria.put("seccion", seccion);

    EditarSeccionView view = new EditarSeccionView(null, true);
    view.setVisible(true);

    Object obj = Memoria.get("seccion");
    if (obj != null && obj.toString().equals("OK")) {
      cargarSecciones();
    }

  }//GEN-LAST:event_btnNuevoActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

    int selectedRow = tblData.getSelectedRow();

    if (selectedRow == -1) {
      return;
    }

    Seccion seccion = secciones.get(selectedRow);

    Memoria.put("accion", UtilView.CRUD_EDITAR);
    Memoria.put("seccion", seccion);

    EditarSeccionView view = new EditarSeccionView(null, true);
    view.setVisible(true);
    

  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int selectedRow = tblData.getSelectedRow();

    if (selectedRow == -1) {
      return;
    }

    Seccion seccion = secciones.get(selectedRow);

    Memoria.put("accion", UtilView.CRUD_ELIMINAR);
    Memoria.put("seccion", seccion);

    EditarSeccionView view = new EditarSeccionView(null, true);
    view.setVisible(true);
    
    
  }//GEN-LAST:event_btnEliminarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCerrar;
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnNuevo;
  private javax.swing.JComboBox<Combo> cboNivel;
  private javax.swing.JComboBox<Combo> cboPeriodo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblData;
  // End of variables declaration//GEN-END:variables

  private void llenarPeriodos() {
    List<Combo> periodos;
    periodos = seccionesController.leerPeriodosProgramar();
    UtilView.llenarCombo(cboPeriodo, periodos);
  }

  private void llenarNiveles() {
    List<Combo> niveles;
    niveles = seccionesController.leerNiveles();
    UtilView.llenarCombo(cboNivel, niveles);
  }

  private void cargarSecciones() {
    // Definir el acceso a la tabla
    DefaultTableModel tabla;
    tabla = (DefaultTableModel) tblData.getModel();
    tabla.setRowCount(0);
    // Leer indices de los combos
    if (!hayCriterio()) {
      return;
    }
    // Valores seleccionados
    Combo periodo = (Combo) cboPeriodo.getSelectedItem();
    Combo nivel = (Combo) cboNivel.getSelectedItem();
    // Traer datos
    secciones = seccionesController.leerSecciones(periodo.getCode(), nivel.getCode());
    // Cargar datos en la tabla
    for (Seccion seccion : secciones) {
      Object[] rowData = {
        seccion.getSeccion(),
        seccion.getNombre(),
        seccion.getPeriodo(),
        seccion.getGrado(),
        seccion.getVacantes(),
        seccion.getMatriculados()
      };
      tabla.addRow(rowData);
    }
  }

  public boolean hayCriterio() {
    boolean estado;
    int indice1 = cboPeriodo.getSelectedIndex();
    int indice2 = cboNivel.getSelectedIndex();
    estado = indice1 > -1 && indice2 > -1;
    return estado;
  }

}
